dbt_us_weather:
  outputs:
    dev:
      dataset: us_weather_alerts_bronze
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /app/airflow/.gcp_keys/us-weather-alert.json
      location: EU
      method: service-account
      priority: interactive
      project: le-wagon-328012
      threads: 1
      type: bigquery
    silver:
      dataset: us_weather_alerts_silver
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /app/airflow/.gcp_keys/us-weather-alert.json
      location: EU
      method: service-account
      priority: interactive
      project: le-wagon-328012
      threads: 1
      type: bigquery
    gold:
      dataset: us_weather_alerts_gold
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /app/airflow/.gcp_keys/us-weather-alert.json
      location: EU
      method: service-account
      priority: interactive
      project: le-wagon-328012
      threads: 1
      type: bigquery
  target: dev
