dbt_us_weather:
  outputs:
    dev:
      dataset: dataSetName
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /app/airflow/.gcp_keys/us_weather_alerts.json
      location: EU
      method: service-account
      priority: interactive
      project: projectId
      threads: 1
      type: bigquery
  target: dev
