[tool.poetry]
name = "us-weather-alerts"
version = "0.1.0"
description = "Le Wagon Data Engineering bootcamp final project"
authors = ["Malte Berneaud <malte.berneaud@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
